language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# CI: Travis home
# BUILD
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# PRE-DEPLOY
before_deploy:
  - zip -r spring-boot-practice.zip *
  - mkdir -p deploy
  - mv spring-boot-practice.zip deploy/

# DEPLOY
# travis with s3 envs
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: build-spring-boot-practice
  region: ap-northeast-2
  acl: private
  local_dir: deploy
  skip_cleanup: true
  on:
    all_branches: true

# NOTIFICATION
notifications:
  email:
    recipients:
      - 'd8726243@gmail.com'