language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# BUILD: Github to TravisCI
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# PRE-DEPLOY
before_deploy:
  - zip -r spring-boot-practice.zip *
  - mkdir -p deploy
  - mv spring-boot-practice.zip deploy/

# DEPLOY: TravisCI to AWS
deploy:
  # TravisCI to S3
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: build-spring-boot-practice
    region: ap-northeast-2
    acl: private
    local_dir: deploy
    skip_cleanup: true
    wait-until-deployed: true
    on:
      all_branches: true
  # S3 to EC2
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: build-spring-boot-practice
    key: spring-boot-practice.zip # Build file
    bundle_type: zip
    application: codedeploy-spring-boot-practice # Codedeploy app
    deployment_group: codedeploy-spring-boot-practice-group # Codedeploy group
    region: ap-northeast-2
    wait_until_deployed: true
    on:
      all_branches: true

# NOTIFICATION
notifications:
  email:
    recipients:
      - 'd8726243@gmail.com'